# used by AWS CodeBuild

version: 0.2
phases:
  install:
    commands:
      - echo "install step"
  pre_build:
    commands:
      - echo "pre_build step"
  build:
    commands:
      - echo "build step"
  post_build:
    commands:
      - echo "post_build step"
      - zip -q -r uclafund-master.zip .
      - aws s3 cp uclafund-master.zip s3://uclafund-source-bucket
