branch-defaults:
  default:
    environment: Uclafundwordpress-php81
deploy:
  artifact: null
environment-defaults:
  UclaFundWordpress-php8:
    branch: null
    repository: null
global:
  application_name: UCLA Fund WordPress
  default_ec2_keyname: null
  default_platform: PHP 8.1
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
